import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MainContainer from "@/components/mainContainer/MainContainer";
import { cookies } from "next/headers";
import { tokenDecode } from "@/functions/tokenDecode";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Basel Sport App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookiesStore = cookies();
  const token = cookiesStore.get("token");
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MainContainer user = {token?tokenDecode(token.value).name:""}>
          {children}
        </MainContainer>
      </body>
    </html>
  );
}
