import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MainContainer from "@/components/mainContainer/MainContainer";
import { UserProvider } from "@/context/userContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Basel Sport App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <UserProvider>
          <MainContainer>
            {children}
        </MainContainer>
        </UserProvider>
      </body>
    </html>
  );
}
